# for now just stores version number and some metadata
author: Korbinian Habereder (a.k.a SecretOne)
co-authors:
  - Jonas Fischer (a.k.a Yleisnero)
version: v0.12.1
includes: 
  - public_config.yaml
