[project]
name = "gmc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "appdirs>=1.4.4",
    "art>=6.5",
    "pyinstaller>=6.15.0",
    "pyyaml>=6.0.2",
]

[dependency-groups]
dev = [
    "ruff>=0.12.11",
]
